# packaging/scripts/docker/docker-compose.yml
version: '3.8'

x-common-volumes: &common-volumes
  volumes:
    - ../../..:/build
    - cargo-cache:/usr/local/cargo/registry
    - package-cache:/build/packaging/build

x-common-environment: &common-environment
  environment:
    - CARGO_HOME=/usr/local/cargo
    - RUSTC_WRAPPER=sccache

services:
  debian-build:
    build:
      context: ../../..
      dockerfile: packaging/scripts/docker/Builders.dockerfile
      target: debian-builder
    <<: *common-volumes
    <<: *common-environment

  void-glibc:
    build:
      context: ../../..
      dockerfile: packaging/scripts/docker/Builders.dockerfile
      target: void-glibc-builder
    volumes:
      - ../../..:/build
      - void-glibc-cargo:/root/.cargo
      - void-glibc-cache:/var/cache/xbps
    working_dir: /build/packaging/build/void/glibc
    init: true

  void-musl:
    build:
      context: ../../..
      dockerfile: packaging/scripts/docker/Builders.dockerfile
      target: void-musl-builder
    volumes:
      - ../../..:/build
      - void-musl-cargo:/root/.cargo
      - void-musl-cache:/var/cache/xbps
    working_dir: /build/packaging/build/void/musl
    init: true

volumes:
  cargo-cache:
  void-glibc-cargo:
  void-glibc-cache:
  void-musl-cargo:
  void-musl-cache:
  package-cache:
