# .cargo/config.toml
[package.metadata.rpm]
package = "azadi-noweb"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
azadi-noweb = { path = "/usr/bin/azadi-noweb" }

[package.metadata.rpm.dependencies]
glibc = ">= 2.28"

[package.metadata.deb]
maintainer = "Gianni Ferrarotti <gianni.ferrarotti@gmail.com>"
copyright = "2024, Gianni Ferrarotti <gianni.ferrarotti@gmail.com>"
license-file = ["LICENSE", "4"]
extended-description = """
A Rust implementation of noweb-style literate programming tool.
Allows developers to write code and documentation in a single source file,
with the ability to extract either the code or documentation as needed."""
depends = "$auto"
section = "devel"
priority = "optional"
assets = [
    ["target/release/azadi-noweb", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/azadi-noweb/README.md", "644"],
]
