# .github/workflows/build.yml
name: Build and Release
on:
  push:
    tags:
      - 'v*'  # Trigger on version tags

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Get version
        id: get_version
        run: |
          chmod +x packaging/scripts/get-version.sh
          echo "version=$(./packaging/scripts/get-version.sh)" >> $GITHUB_OUTPUT

  build:
    needs: version
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            artifact_extension: ''
            asset_name: azadi-noweb-linux
          - os: windows-latest
            artifact_extension: '.exe'
            asset_name: azadi-noweb-windows.exe
          - os: macos-latest
            artifact_extension: ''
            asset_name: azadi-noweb-macos
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Prepare asset
        shell: bash
        run: |
          cp "target/release/azadi-noweb${{ matrix.artifact_extension }}" "${{ matrix.asset_name }}"

      - name: Create Release
        if: matrix.os == 'ubuntu-24.04'
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          files: ${{ matrix.asset_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
