name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      - run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: azadi-noweb-${{ matrix.os }}
          path: target/release/azadi-noweb
          path: target/release/azadi-noweb.exe
