name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        run: cargo build --release
      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: azadi-noweb-${{ matrix.os }}
          path: target/release/azadi-noweb
