name: Build Void Package

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build-glibc:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/void-linux/void-linux:latest-full-x86_64
      options: --init
    steps:
      - name: Update XBPS
        shell: sh
        run: |
          xbps-install -S
          xbps-install -yu xbps

      - name: Install basic dependencies
        shell: sh
        run: |
          xbps-install -Syu
          xbps-install -y bash git gcc libstdc++

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download package files
        uses: actions/download-artifact@v4
        with:
          name: package-files
          path: /home/builder/packaging/build

      - name: Install build dependencies
        shell: bash
        run: |
          xbps-install -y base-devel rust cargo

      - name: Build package
        shell: bash
        run: |
          cd /home/builder/packaging/build/void/glibc
          # Copy template to proper location
          mkdir -p /usr/src/void-packages/srcpkgs/azadi-noweb
          cp template /usr/src/void-packages/srcpkgs/azadi-noweb/template
          # Clone void-packages
          git clone --depth 1 https://github.com/void-linux/void-packages
          cd void-packages
          # Set up environment
          ./xbps-src binary-bootstrap
          # Build package
          ./xbps-src pkg azadi-noweb

      - name: Test package
        shell: bash
        run: |
          xbps-rindex -a hostdir/binpkgs/azadi-noweb-*.xbps
          xbps-install -y hostdir/binpkgs/azadi-noweb-*.xbps
          azadi-noweb --version
          azadi-noweb --help

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: void-glibc-package
          path: void-packages/hostdir/binpkgs/azadi-noweb-*.xbps

  build-musl:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/void-linux/void-linux:latest-full-x86_64-musl
      options: --init
    steps:
      - name: Update XBPS
        shell: sh
        run: |
          xbps-install -S
          xbps-install -yu xbps

      - name: Install basic dependencies
        shell: sh
        run: |
          xbps-install -Syu
          xbps-install -y bash git gcc gcompat

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download package files
        uses: actions/download-artifact@v4
        with:
          name: package-files
          path: /home/builder/packaging/build

      - name: Install build dependencies
        shell: bash
        run: |
          xbps-install -y base-devel rust cargo

      - name: Build package
        shell: bash
        run: |
          cd /home/builder/packaging/build/void/musl
          # Copy template to proper location
          mkdir -p /usr/src/void-packages/srcpkgs/azadi-noweb
          cp template /usr/src/void-packages/srcpkgs/azadi-noweb/template
          # Clone void-packages
          git clone --depth 1 https://github.com/void-linux/void-packages
          cd void-packages
          # Set up environment
          ./xbps-src binary-bootstrap
          # Build package
          ./xbps-src pkg azadi-noweb

      - name: Test package
        shell: bash
        run: |
          xbps-rindex -a hostdir/binpkgs/azadi-noweb-*.xbps
          xbps-install -y hostdir/binpkgs/azadi-noweb-*.xbps
          azadi-noweb --version
          azadi-noweb --help

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: void-musl-package
          path: void-packages/hostdir/binpkgs/azadi-noweb-*.xbps
