# .github/workflows/packages-debian.yml
name: Build Debian Package

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download package files
        uses: actions/download-artifact@v4
        with:
          name: package-files
          path: packaging/build

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build package
        run: |
          docker-compose -f packaging/scripts/docker/docker-compose.yml \
            run --rm debian-build

      - name: Test package
        run: |
          sudo dpkg -i packaging/build/deb/*.deb
          azadi-noweb --version
          azadi-noweb --help

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: debian-package
          path: packaging/build/deb/*.deb
