name: Build and Release Packages
on:
  push:
    tags:
      - 'v*'

jobs:
  generate:
    uses: ./.github/workflows/packages-generate.yml

  alpine:
    needs: generate
    uses: ./.github/workflows/packages-alpine.yml
    with:
      version: ${{ needs.generate.outputs.version }}

  arch:
    needs: generate
    uses: ./.github/workflows/packages-arch.yml
    with:
      version: ${{ needs.generate.outputs.version }}

  void:
    needs: generate
    uses: ./.github/workflows/packages-void.yml
    with:
      version: ${{ needs.generate.outputs.version }}

  release:
    needs: [generate, alpine, arch, void]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/alpine-package/*
            artifacts/arch-package/*
            artifacts/void-glibc-package/*
            artifacts/void-musl-package/*
          generate_release_notes: true
