name: Build Void Package

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build-glibc:
    runs-on: ubuntu-latest
    container: ghcr.io/void-linux/void-linux:latest-full-x86_64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download package files
        uses: actions/download-artifact@v4
        with:
          name: package-files
          path: /home/builder/packaging/build

      - name: Install build dependencies
        shell: bash
        run: |
          xbps-install -Syu
          xbps-install -y base-devel git rust cargo

      - name: Build package
        shell: bash
        run: |
          cd /home/builder/packaging/build/void
          ./build.sh

      - name: Test package
        shell: bash
        run: |
          xbps-rindex -a *.xbps
          xbps-install -y *.xbps
          azadi-noweb --version
          azadi-noweb --help

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: void-glibc-package
          path: /home/builder/packaging/build/void/*.xbps

  build-musl:
    runs-on: ubuntu-latest
    container: ghcr.io/void-linux/void-linux:latest-full-x86_64-musl
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download package files
        uses: actions/download-artifact@v4
        with:
          name: package-files
          path: /home/builder/packaging/build

      - name: Install build dependencies
        shell: bash
        run: |
          xbps-install -Syu
          xbps-install -y base-devel git rust cargo

      - name: Build package
        shell: bash
        run: |
          cd /home/builder/packaging/build/void
          ./build.sh

      - name: Test package
        shell: bash
        run: |
          xbps-rindex -a *.xbps
          xbps-install -y *.xbps
          azadi-noweb --version
          azadi-noweb --help

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: void-musl-package
          path: /home/builder/packaging/build/void/*.xbps

