name: Build Arch Package
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: package-files
          path: packaging/build

      - name: Install build dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm rust cargo git

      - name: Build package
        run: |
          cd packaging/build/arch
          makepkg -si --noconfirm

      - name: Test package
        run: |
          pacman -U --noconfirm *.pkg.tar.zst
          azadi-noweb --version
          azadi-noweb --help

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: arch-package
          path: packaging/build/arch/*.pkg.tar.zst
