name: Build Arch Package

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up non-root user
        shell: bash
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder:builder .

      - name: Download package files
        uses: actions/download-artifact@v4
        with:
          name: package-files
          path: /home/builder/packaging/build

      - name: Install build dependencies
        shell: bash
        run: |
          sudo pacman -Syu --noconfirm
          sudo pacman -S --noconfirm rust cargo git

      - name: Build package
        shell: bash
        run: |
          cd /home/builder/packaging/build/arch
          sudo -u builder makepkg -si --noconfirm
        env:
          HOME: /home/builder

      - name: Test package
        shell: bash
        run: |
          pacman -U --noconfirm *.pkg.tar.zst
          azadi-noweb --version
          azadi-noweb --help
        env:
          HOME: /home/builder

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: arch-package
          path: /home/builder/packaging/build/arch/*.pkg.tar.zst
