name: Build Void Package

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build-glibc:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/void-linux/void-linux:latest-full-x86_64
      options: --init --privileged
    steps:
      - name: Update XBPS
        shell: sh
        run: |
          xbps-install -S
          xbps-install -yu xbps

      - name: Install basic dependencies
        shell: sh
        run: |
          xbps-install -Syu
          xbps-install -y bash git gcc libstdc++ sudo

      - name: Set up build directories
        shell: sh
        run: |
          mkdir -p /usr/src
          chmod 777 /usr/src

          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder:builder /home/builder

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download package files
        uses: actions/download-artifact@v4
        with:
          name: package-files
          path: /home/builder/packaging/build

      - name: Install build dependencies
        shell: bash
        run: |
          xbps-install -y base-devel rust cargo

      - name: Build package
        shell: bash
        run: |
          cd /home/builder/packaging/build/void/glibc
          chown -R builder:builder .

          su builder -c '
            cd /usr/src
            git clone --depth 1 https://github.com/void-linux/void-packages
            cd void-packages

            mkdir -p srcpkgs/azadi-noweb
            cp /home/builder/packaging/build/void/glibc/template srcpkgs/azadi-noweb/

            ./xbps-src binary-bootstrap
            ./xbps-src pkg azadi-noweb
          '

      - name: Test package
        shell: bash
        run: |
          cd /usr/src/void-packages
          xbps-rindex -a hostdir/binpkgs/azadi-noweb-*.xbps
          xbps-install -y hostdir/binpkgs/azadi-noweb-*.xbps
          azadi-noweb --version
          azadi-noweb --help

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: void-glibc-package
          path: /usr/src/void-packages/hostdir/binpkgs/azadi-noweb-*.xbps

  build-musl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download package files
        uses: actions/download-artifact@v4
        with:
          name: package-files
          path: packaging/build

      - name: Build in container
        run: |
          docker run --rm --privileged -v ${{ github.workspace }}:/workspace \
            ghcr.io/void-linux/void-linux:latest-full-x86_64-musl \
            sh -c '
              set -ex
              xbps-install -S
              xbps-install -yu xbps
              xbps-install -Syu
              xbps-install -y bash git gcc gcompat base-devel rust cargo sudo

              mkdir -p /usr/src
              chmod 777 /usr/src

              useradd -m builder
              echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
              chown -R builder:builder /workspace

              su builder -c "
                cd /usr/src
                git clone --depth 1 https://github.com/void-linux/void-packages
                cd void-packages

                mkdir -p srcpkgs/azadi-noweb
                cp /workspace/packaging/build/void/musl/template srcpkgs/azadi-noweb/

                ./xbps-src binary-bootstrap
                ./xbps-src pkg azadi-noweb
              "
              cp /usr/src/void-packages/hostdir/binpkgs/azadi-noweb-*.xbps /workspace/
              chown root:root /workspace/azadi-noweb-*.xbps
            '

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: void-musl-package
          path: azadi-noweb-*.xbps
