name: Build Alpine Package

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
      options: --init
    steps:
      - name: Install base dependencies
        run: |
          apk add --no-cache alpine-sdk git sudo

      - name: Setup builder user
        run: |
          adduser -D builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          addgroup builder abuild

          # Setup abuild for builder user
          su builder -c "abuild-keygen -a -n"

          # Give builder ownership of package dir
          mkdir -p /var/cache/distfiles
          chown -R builder:builder /var/cache/distfiles

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download package files
        uses: actions/download-artifact@v4
        with:
          name: package-files
          path: /home/builder/packaging/build

      - name: Build package
        run: |
          cd /home/builder/packaging/build/alpine
          chown -R builder:builder .
          # Generate checksums first, then build
          su builder -c '
            abuild checksum
            abuild -r
          '

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: alpine-package
          path: /home/builder/packages/*/x86_64/*.apk
