name: Build Void Package

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build-glibc:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/void-linux/void-linux:latest-full-x86_64
      options: --init
    steps:
      - name: Update XBPS
        shell: sh
        run: |
          xbps-install -S
          xbps-install -yu xbps

      - name: Install basic dependencies
        shell: sh
        run: |
          xbps-install -Syu
          xbps-install -y bash git gcc libstdc++

      - name: Set up builder user
        shell: sh
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder:builder /home/builder

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download package files
        uses: actions/download-artifact@v4
        with:
          name: package-files
          path: /home/builder/packaging/build

      - name: Install build dependencies
        shell: bash
        run: |
          xbps-install -y base-devel rust cargo

      - name: Build package
        shell: bash
        run: |
          cd /home/builder/packaging/build/void/glibc
          # Set up build environment
          sudo -u builder bash -c '
            mkdir -p /usr/src/void-packages/srcpkgs/azadi-noweb
            cp template /usr/src/void-packages/srcpkgs/azadi-noweb/template
            git clone --depth 1 https://github.com/void-linux/void-packages
            cd void-packages
            ./xbps-src binary-bootstrap
            ./xbps-src pkg azadi-noweb
          '

      - name: Test package
        shell: bash
        run: |
          cd /home/builder/void-packages
          xbps-rindex -a hostdir/binpkgs/azadi-noweb-*.xbps
          xbps-install -y hostdir/binpkgs/azadi-noweb-*.xbps
          azadi-noweb --version
          azadi-noweb --help

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: void-glibc-package
          path: /home/builder/void-packages/hostdir/binpkgs/azadi-noweb-*.xbps

  build-musl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download package files
        uses: actions/download-artifact@v4
        with:
          name: package-files
          path: packaging/build

      - name: Build in container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace \
            ghcr.io/void-linux/void-linux:latest-full-x86_64-musl \
            sh -c '
              set -ex
              # System updates
              xbps-install -S
              xbps-install -yu xbps
              xbps-install -Syu
              xbps-install -y bash git gcc gcompat base-devel rust cargo

              # Create builder user
              useradd -m builder
              echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
              chown -R builder:builder /workspace

              # Build as builder user
              sudo -u builder bash -c "
                cd /workspace/packaging/build/void/musl
                mkdir -p /usr/src/void-packages/srcpkgs/azadi-noweb
                cp template /usr/src/void-packages/srcpkgs/azadi-noweb/template
                git clone --depth 1 https://github.com/void-linux/void-packages
                cd void-packages
                ./xbps-src binary-bootstrap
                ./xbps-src pkg azadi-noweb
              "
              # Copy artifacts out with proper permissions
              cp void-packages/hostdir/binpkgs/azadi-noweb-*.xbps /workspace/
              chown root:root /workspace/azadi-noweb-*.xbps
            '

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: void-musl-package
          path: azadi-noweb-*.xbps
